import { MarketCatalyst, BitgetSignalSkill } from '../types/signals';

export class SignalAggregatorService {
  private static mockCatalysts: MarketCatalyst[] = [
    {
      id: "cat-nvda-weekend-01",
      timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(), // 18m ago
      sourceSkill: "news-briefing",
      title: "US Commerce Dept Issues Weekend Clarification on High-Density AI Accelerators",
      summary: "Sunday 6:30 PM: Department of Commerce clarifies licensing rules for Blackwell architecture chips to tier-2 cloud providers in Middle East. Removes previously rumored export blanket ban overhang.",
      relevantTickers: ["rNVDA"],
      urgency: "HIGH",
      sentiment: "BULLISH",
      confidenceScore: 89,
      sourceCitation: "US Bureau of Industry & Security (BIS) Bulletin #2026-0814 & Taipei Times",
      sourceUrl: "https://www.bis.doc.gov/",
      directQuote: "Specific licensing exemptions established for localized high-density interconnect cluster deployments.",
      shockScore: 0.89,
      assetBeta: 1.45,
      falsificationCondition: "Invalidate if Sunday Night S&P 500 futures open down ≥ 0.8% or Commerce Dept issues formal retraction.",
      metadata: {
        headlineImpact: "+3.2% projected repricing at Monday 9:30 AM open based on historical policy resolutions.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "GEOPOLITICAL_TECH_POLICY",
      },
    },
    {
      id: "cat-tsla-overnight-02",
      timestamp: new Date(Date.now() - 1000 * 60 * 42).toISOString(), // 42m ago
      sourceSkill: "sentiment-analyst",
      title: "Tesla FSD v13 Chinese Regulatory Fast-Track Granted in Shanghai Free-Trade Zone",
      summary: "Sunday night reports confirm municipal approval for full driverless robo-fleet road testing permits beginning next month. Social sentiment surged +410% in 1 hour.",
      relevantTickers: ["rTSLA"],
      urgency: "HIGH",
      sentiment: "BULLISH",
      confidenceScore: 84,
      sourceCitation: "Shanghai Municipal Transportation Commission Public Notice & Caixin Global",
      sourceUrl: "https://www.caixinglobal.com/",
      directQuote: "Municipal pilot permit granted for commercial validation of vision-based level-4 autonomous fleets in Pudong.",
      shockScore: 0.84,
      assetBeta: 1.62,
      falsificationCondition: "Invalidate if Chinese Ministry of Industry and Information Technology denies pilot scope expansion.",
      metadata: {
        headlineImpact: "Robo-fleet expansion unlocks high-margin recurring software monetization in world's largest EV market.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "AUTONOMOUS_MOBILITY",
      },
    },
    {
      id: "cat-mstr-weekend-03",
      timestamp: new Date(Date.now() - 1000 * 60 * 75).toISOString(), // 75m ago
      sourceSkill: "market-intel",
      title: "Bitcoin Surges Past $68.5k on Weekend Spot ETF Inflow Momentum",
      summary: "Weekend crypto liquidity pushed BTC through key resistance. Historical beta of MicroStrategy (MSTR) against weekend BTC surge implies a +5.4% opening gap on Monday.",
      relevantTickers: ["rMSTR", "rCOIN"],
      urgency: "MEDIUM",
      sentiment: "BULLISH",
      confidenceScore: 91,
      sourceCitation: "SEC Form 8-K / MicroStrategy Treasury Disclosure & Bloomberg Onchain Terminal",
      sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0001050446",
      directQuote: "MicroStrategy acquired an aggregate of 7,420 bitcoins for approx $498.5 million in cash.",
      shockScore: 0.91,
      assetBeta: 2.15,
      falsificationCondition: "Invalidate if BTC retraces below $66,200 weekend support before 8:00 PM EST Sunday futures open.",
      metadata: {
        headlineImpact: "Direct net asset value (NAV) expansion for MSTR treasury holdings ahead of US equity open.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "ONCHAIN_LIQUIDITY",
      },
    },
    {
      id: "cat-macro-fed-04",
      timestamp: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
      sourceSkill: "macro-analyst",
      title: "Fed Governor Weekend Speech Signals Front-Loaded 50bps Rate Cut Trajectory",
      summary: "Sunday academic symposium remarks emphasize softening labor conditions and real rate restrictive drag. 2-Year Treasury futures imply lower yield open.",
      relevantTickers: ["rMSFT", "rAAPL"],
      urgency: "MEDIUM",
      sentiment: "BULLISH",
      confidenceScore: 78,
      sourceCitation: "Federal Reserve Board Speech Transcript & CME FedWatch Tool",
      sourceUrl: "https://www.federalreserve.gov/newsevents/speeches.htm",
      directQuote: "Labor market indicators warrant front-loaded recalibration toward neutral policy settings.",
      shockScore: 0.78,
      assetBeta: 1.18,
      falsificationCondition: "Invalidate if 2-Year Treasury yield futures rebound above 4.12%.",
      metadata: {
        headlineImpact: "Discount rate reduction expands valuation multiple headroom for megacap tech equities.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "FED_POLICY",
      },
    },
    {
      id: "cat-pltr-dod-05",
      timestamp: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
      sourceSkill: "news-briefing",
      title: "Palantir Awarded $480M Defense Department Contract Expansion for JADC2 Maven Deployment",
      summary: "Weekend Department of Defense contract awards ledger confirms ceiling expansion for AI battle-management software deployment across INDOPACOM command nodes.",
      relevantTickers: ["rPLTR"],
      urgency: "HIGH",
      sentiment: "BULLISH",
      confidenceScore: 93,
      sourceCitation: "US Department of Defense (DoD) Daily Contracting Digest #FA8730-26-C-0042",
      sourceUrl: "https://www.defense.gov/News/Contracts/",
      directQuote: "Palantir USG Inc awarded firm-fixed-price modification for scalable machine-learning enterprise integration.",
      shockScore: 0.93,
      assetBeta: 1.85,
      falsificationCondition: "Invalidate if Congressional Armed Services Committee issues spending deferral notice.",
      metadata: {
        headlineImpact: "High-margin defense ARR expansion with zero hardware supply-chain dependency.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "DEFENSE_AI",
      },
    },
    {
      id: "cat-aapl-foxconn-06",
      timestamp: new Date(Date.now() - 1000 * 60 * 190).toISOString(),
      sourceSkill: "market-intel",
      title: "Foxconn Submits $1.4B Fab Expansion Filing in Hai Duong for M5 Neural Processing Units",
      summary: "Weekend regulatory filings in Vietnam confirm accelerated fab line conversion to support Apple M5 Silicon packaging with TSMC CoWoS advanced substrate integration.",
      relevantTickers: ["rAAPL"],
      urgency: "MEDIUM",
      sentiment: "BULLISH",
      confidenceScore: 82,
      sourceCitation: "Taipei Economic Daily & Vietnam Ministry of Planning and Investment Registry",
      sourceUrl: "https://money.udn.com/",
      directQuote: "Approved investment license for advanced microelectronics modular assembly facility in Hai Duong.",
      shockScore: 0.82,
      assetBeta: 1.12,
      falsificationCondition: "Invalidate if TSMC reports packaging yield degradation below 85%.",
      metadata: {
        headlineImpact: "De-risks Southeast Asia hardware pipeline ahead of Q4 consumer cycle.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "HARDWARE_SUPPLY_CHAIN",
      },
    },
    {
      id: "cat-msft-openai-07",
      timestamp: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
      sourceSkill: "news-briefing",
      title: "Microsoft Azure Finalizes Multi-Gigawatt Dedicated Power Agreement for Next-Gen Clusters",
      summary: "Sunday utility commission filings confirm 2.2 GW nuclear and renewable PPA execution for Mount Pleasant hyperscale datacenter expansion dedicated to OpenAI training runs.",
      relevantTickers: ["rMSFT"],
      urgency: "HIGH",
      sentiment: "BULLISH",
      confidenceScore: 88,
      sourceCitation: "Wisconsin Public Service Commission Docket #6680-CE-184 & Bloomberg Tech Wire",
      sourceUrl: "https://psc.wi.gov/",
      directQuote: "Long-term clean energy procurement agreement secured for continuous base-load computing infrastructure.",
      shockScore: 0.88,
      assetBeta: 1.22,
      falsificationCondition: "Invalidate if state utility board imposes transmission capacity interconnection moratorium.",
      metadata: {
        headlineImpact: "Removes primary compute-capacity bottleneck for Azure cloud revenue expansion.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "DATACENTER_ENERGY",
      },
    },
    {
      id: "cat-pelosi-nvda-08",
      timestamp: new Date(Date.now() - 1000 * 60 * 260).toISOString(),
      sourceSkill: "sentiment-analyst",
      title: "STOCK Act Disclosure: Nancy Pelosi Discloses Purchase of 50x NVDA $120 Calls ($1.25M Notional)",
      summary: "House Ethics Periodic Transaction Report confirms purchase of deep in-the-money call options expiring June 2027. Social sentiment index surged +340% within 30 minutes.",
      relevantTickers: ["rNVDA"],
      urgency: "HIGH",
      sentiment: "BULLISH",
      confidenceScore: 92,
      sourceCitation: "U.S. House of Representatives Ethics Committee Periodic Transaction Report #2026-04192",
      sourceUrl: "https://disclosures-clerk.house.gov/PublicDisclosure/FinancialDisclosure",
      directQuote: "Purchase transaction of NVIDIA Corp call options with strike price $120.00, valued between $1,000,001 - $5,000,000.",
      shockScore: 0.92,
      assetBeta: 1.45,
      falsificationCondition: "Invalidate if House clerk posts amendment clarifying filing was a routine blind trust execution.",
      metadata: {
        headlineImpact: "High-conviction retail copy-trading inflow momentum ahead of Monday equity open.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "CONGRESSIONAL_TRADE",
      },
    },
    {
      id: "cat-coin-sec-09",
      timestamp: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
      sourceSkill: "market-intel",
      title: "SEC Division of Trading & Markets Releases Favorable Clearinghouse Digital Custody Guidance",
      summary: "Sunday public guidance clarifies non-objection status for regulated broker-dealers holding reserves with institutional qualified custodians including Coinbase Custody Trust.",
      relevantTickers: ["rCOIN"],
      urgency: "HIGH",
      sentiment: "BULLISH",
      confidenceScore: 89,
      sourceCitation: "SEC Division of Trading and Markets Staff Statement & Reuters Financial Regulatory",
      sourceUrl: "https://www.sec.gov/news/statements",
      directQuote: "Staff will not recommend enforcement action regarding qualified custody segmentation practices under Rule 15c3-3.",
      shockScore: 0.89,
      assetBeta: 2.35,
      falsificationCondition: "Invalidate if SEC Commissioners issue conflicting policy memorandum.",
      metadata: {
        headlineImpact: "Substantially lowers regulatory compliance capital charge for institutional crypto onboarding.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "SEC_REGULATORY",
      },
    },
    {
      id: "cat-amzn-trainium-10",
      timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
      sourceSkill: "news-briefing",
      title: "AWS Deploys 100k Trainium2 Custom AI Chips in Production for Anthropic Claude Workloads",
      summary: "Amazon Web Services confirms production deployment of Project Rainier cluster, reducing reliance on third-party GPU margins and lowering inference unit costs by 35%.",
      relevantTickers: ["rAMZN"],
      urgency: "MEDIUM",
      sentiment: "BULLISH",
      confidenceScore: 85,
      sourceCitation: "AWS Official Architecture Blog & IEEE Microelectronics Review",
      sourceUrl: "https://aws.amazon.com/blogs/aws/",
      directQuote: "UltraCluster scaling demonstrates 35% lower cost-to-train metrics across multi-tier transformer models.",
      shockScore: 0.85,
      assetBeta: 1.25,
      falsificationCondition: "Invalidate if Anthropic reports benchmark throughput parity failure against H100 baselines.",
      metadata: {
        headlineImpact: "Proprietary silicon gross margin expansion for AWS hyperscale segment.",
        underlyingUSMarketStatus: "CLOSED_WEEKEND",
        macroTag: "CUSTOM_SILICON",
      },
    },
  ];

  static async getActiveCatalysts(): Promise<MarketCatalyst[]> {
    return [...this.mockCatalysts];
  }

  static async getCatalystById(id: string): Promise<MarketCatalyst | null> {
    const found = this.mockCatalysts.find(c => c.id === id);
    return found || null;
  }

  static async injectCustomCatalyst(catalyst: Omit<MarketCatalyst, 'id' | 'timestamp'>): Promise<MarketCatalyst> {
    const newEntry: MarketCatalyst = {
      ...catalyst,
      id: `cat-${Date.now().toString(36)}`,
      timestamp: new Date().toISOString(),
    };
    this.mockCatalysts.unshift(newEntry);
    return newEntry;
  }
}
