import React from 'react';
import { ShieldAlert, Lock, CheckCircle2 } from 'lucide-react';

export const DisclaimerBanner: React.FC = () => {
  return (
    <div className="w-full bg-slate-950/80 border-b border-cyan-500/20 px-4 py-2 text-xs">
      <div className="max-w-7xl mx-auto flex flex-wrap items-center justify-between gap-2 text-slate-400">
        <div className="flex items-center gap-2">
          <ShieldAlert className="w-3.5 h-3.5 text-cyan-400 flex-shrink-0" />
          <span>
            <strong className="text-cyan-300 font-medium">HACKATHON EVALUATION MODE:</strong> Informational only, not investment advice. All proposals generated by AI agent; human approval is mandatory.
          </span>
        </div>
        <div className="flex items-center gap-4 text-[11px]">
          <span className="flex items-center gap-1 text-emerald-400">
            <Lock className="w-3 h-3" /> Bitget Agentic Account Isolated
          </span>
          <span className="flex items-center gap-1 text-cyan-400">
            <CheckCircle2 className="w-3 h-3" /> Mode: <code className="bg-cyan-950/60 text-cyan-300 px-1 py-0.5 rounded font-mono">--paper-trading</code>
          </span>
          <span className="text-slate-500 hidden sm:inline">
            Zero real withdrawals allowed
          </span>
        </div>
      </div>
    </div>
  );
};
